# Generated by Django 6.0.4 on 2026-04-15 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120, unique=True)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("PUSH", "Push"),
                            ("PULL", "Pull"),
                            ("LEGS", "Jambes"),
                            ("CORE", "Gainage"),
                            ("FULL_BODY", "Full body"),
                            ("OTHER", "Autre"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "exercice",
                "verbose_name_plural": "exercices",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="SeanceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "seance type",
                "verbose_name_plural": "seances types",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Seance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PLANIFIEE", "Planifiee"),
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminee"),
                        ],
                        default="PLANIFIEE",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "seance_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seances",
                        to="workouts.seancetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "seance",
                "verbose_name_plural": "seances",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SessionLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre_prevu", models.PositiveSmallIntegerField()),
                ("ordre_reel", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("numero_serie", models.PositiveSmallIntegerField()),
                (
                    "repetitions_cible",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "charge_cible",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "rpe_cible",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "repos_secondes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("tempo", models.CharField(blank=True, max_length=30)),
                (
                    "repetitions_reelles",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "charge_reelle",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "rpe_reel",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_lignes",
                        to="workouts.exercice",
                    ),
                ),
                (
                    "seance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="workouts.seance",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de session",
                "verbose_name_plural": "lignes de session",
                "ordering": ["seance", "ordre_reel", "ordre_prevu", "numero_serie"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("seance", "ordre_prevu", "numero_serie"),
                        name="unique_session_serie_par_ordre_prevu",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("rpe_cible__isnull", True),
                            models.Q(("rpe_cible__gte", 0), ("rpe_cible__lte", 10)),
                            _connector="OR",
                        ),
                        name="session_rpe_cible_entre_0_et_10",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("rpe_reel__isnull", True),
                            models.Q(("rpe_reel__gte", 0), ("rpe_reel__lte", 10)),
                            _connector="OR",
                        ),
                        name="session_rpe_reel_entre_0_et_10",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TemplateLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre_exercice", models.PositiveSmallIntegerField()),
                ("numero_serie", models.PositiveSmallIntegerField()),
                (
                    "repetitions_cible",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "charge_cible",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "rpe_cible",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "repos_secondes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("tempo", models.CharField(blank=True, max_length=30)),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_lignes",
                        to="workouts.exercice",
                    ),
                ),
                (
                    "seance_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="workouts.seancetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de template",
                "verbose_name_plural": "lignes de template",
                "ordering": ["seance_type", "ordre_exercice", "numero_serie"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("seance_type", "ordre_exercice", "numero_serie"),
                        name="unique_template_serie_par_ordre",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("rpe_cible__isnull", True),
                            models.Q(("rpe_cible__gte", 0), ("rpe_cible__lte", 10)),
                            _connector="OR",
                        ),
                        name="template_rpe_cible_entre_0_et_10",
                    ),
                ],
            },
        ),
    ]
