# Generated by Django 6.0.4 on 2026-04-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionligne",
            name="validee",
            field=models.BooleanField(default=False),
        ),
    ]
