# Generated by Django 6.0.4 on 2026-04-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_sessionligne_validee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercice",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("ADDUCTEURS", "Adducteurs"),
                    ("ABDOS", "Abdos"),
                    ("CARDIO", "Cardio"),
                    ("DOS", "Dos"),
                    ("EPAULE_ARRIERE", "Epaule arriere"),
                    ("FESSIERS", "Fessiers"),
                    ("GAINAGE", "Gainage"),
                    ("ISCHIOS", "Ischios"),
                    ("PECTORAUX", "Pectoraux"),
                    ("QUADRICEPS", "Quadriceps"),
                    ("OTHER", "Autre"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
