# Generated by Django 6.0.4 on 2026-04-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_backfill_ordre_reel_explicit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('poids', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('tour_poitrine', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de poitrine (cm)')),
                ('tour_taille', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de taille (cm)')),
                ('tour_hanches', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de hanches (cm)')),
                ('tour_bras', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de bras (cm)')),
                ('tour_cuisse', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de cuisse (cm)')),
                ('masse_grasse', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='% masse grasse')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'mensuration',
                'verbose_name_plural': 'mensurations',
                'ordering': ['-date'],
            },
        ),
    ]
